spring:
  application:
    name: micro-course
  datasource:
    url: jdbc:postgresql://localhost:5432/micro_course
    username: postgres
    password: sasa1975
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: true
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8002
logging:
  level:
    org.hibernate.sql: debug